import type { Locale } from "@/lib/types";

const copy = {
  ru: {
    common: {
      loading: "Загружаем кабинет",
      noData: "Пока нет данных для этого раздела.",
      open: "Открыть",
      manage: "Управлять",
      status: "Статус",
      date: "Дата",
      all: "Всего",
      active: "Активные",
      pending: "Ожидают",
      upcoming: "Ближайшие",
      cancelled: "Отмененные",
      completed: "Завершенные",
      bracketReady: "Сетка готова",
      bracketNeeded: "Нужно сгенерировать",
      noBracket: "Сетки нет",
      profile: "Профиль",
      quickActions: "Быстрые действия",
      latestActivity: "Последняя активность",
      emptyActivity: "Новых событий пока нет.",
      table: "Стол",
      player: "Игрок",
      club: "Клуб",
      tournament: "Турнир",
      booking: "Бронь",
      application: "Заявка"
    },
    admin: {
      eyebrow: "Admin dashboard",
      title: "Панель управления платформой",
      subtitle: "Сводка по пользователям, бильярдным, турнирам, броням и заявкам на одной странице.",
      users: "Пользователи",
      clubs: "Бильярдные",
      tournaments: "Турниры",
      bookings: "Брони",
      pendingApplications: "Заявки на модерации",
      actionsTitle: "Быстрый вход в управление",
      activityTitle: "Сводка последних событий",
      activitySubtitle: "Собрано из реальных пользователей, турниров, заявок и броней.",
      actions: {
        tournaments: "Открыть управление турнирами",
        clubs: "Открыть управление бильярдными",
        applications: "Проверить заявки",
        users: "Управлять пользователями",
        news: "Управлять новостями"
      },
      actionDescriptions: {
        tournaments: "Создание, статусы, сетки и публичная карточка турнира.",
        clubs: "Профили мест, адреса, столы и контактные данные.",
        applications: "Одобрение и отклонение заявок игроков.",
        users: "Роли, доступ и проверка аккаунтов.",
        news: "Публикации и новости платформы."
      },
      emptyBookings: "Броней пока нет.",
      emptyApplications: "Новых заявок нет."
    },
    organizer: {
      eyebrow: "Organizer dashboard",
      title: "Рабочий кабинет организатора",
      subtitle: "Турниры, заявки, пул участников и состояние сеток в одном рабочем месте.",
      create: "Создать турнир",
      myTournaments: "Мои турниры",
      myTournamentsSubtitle: "Ближайшие и активные турниры с подсказками по следующему действию.",
      upcoming: "Ближайшие турниры",
      liveFinished: "Live и завершенные",
      pendingApplications: "Заявки ждут решения",
      participantPool: "Участники в пуле",
      bracketStatus: "Состояние сеток",
      needsResult: "Нужно внести результаты",
      generateBracket: "Сгенерировать сетку",
      moderate: "Модерировать заявки",
      openTournament: "Открыть турнир",
      noTournaments: "У вас пока нет турниров. Создайте первый турнир, чтобы открыть регистрацию и собрать участников.",
      noAttention: "Срочных действий сейчас нет.",
      createTitle: "Новый турнир",
      createSubtitle: "Минимальная форма создает рабочий турнир. Подробности, регламент и сетка настраиваются в управлении турниром.",
      successCreated: "Турнир создан.",
      createClub: "Открыть бронирование",
      noClubForTournament: "Нет доступных бильярдных мест. Обратитесь к администратору.",
      createFailed: "Не удалось создать турнир. Проверьте поля и попробуйте еще раз.",
      drawCompleted: "Жеребьевка проведена. Сетка создана, турнир переведен в LIVE.",
      form: {
        mainBlock: "Основное",
        mainBlockHelp: "Название, место проведения и дисциплина турнира.",
        paramsBlock: "Параметры турнира",
        paramsBlockHelp: "Размер сетки, призовой фонд и статус турнира.",
        publicBlock: "Публичная информация",
        publicBlockHelp: "Эти тексты увидят игроки на странице турнира.",
        title: "Название турнира",
        titlePlaceholder: "Например: Tashkent Open 2026",
        startsAt: "Дата и время начала",
        startsAtPlaceholder: "Выберите дату и время начала",
        club: "Бильярдная (где проходит турнир)",
        clubEmptyOption: "Сначала добавьте бильярдную через администратора",
        discipline: "Дисциплина",
        category: "Категория",
        tournamentType: "Тип турнира",
        format: "Формат",
        bracketType: "Тип сетки",
        prizePool: "Призовой фонд (сум)",
        prizePoolPlaceholder: "Например: 500000",
        prizePoolHelp: "Общий призовой фонд турнира",
        bracketSize: "Количество участников",
        bracketSizeHelp: "Сколько игроков будет в сетке (2, 4, 8, 16, 32, 64)",
        status: "Статус турнира",
        statusHelp: "Регистрация — игроки могут подавать заявки",
        registrationLabel: "Статус для игроков (что они видят)",
        registrationLabelPlaceholder: "Например: Регистрация открыта до 10 мая",
        description: "Описание турнира",
        descriptionPlaceholder: "Опишите правила, условия участия и особенности турнира",
        participantMode: "Тип набора участников",
        applicationsMode: "Через заявки",
        manualMode: "Ручная жеребьёвка",
        participantModeHelp: "Через заявки — текущий flow с модерацией. Ручная жеребьёвка — просто введите имена и сразу создайте сетку.",
        manualListTitle: "Список участников",
        manualListHelp: "Введите имена реальных игроков. Пользователи не создаются — участники сохраняются только как имена в этой сетке.",
        participantNamePlaceholder: "Например: Али",
        addParticipant: "Добавить игрока",
        removeParticipant: "Удалить",
        participantNameLabel: "Имя игрока",
        manualEmpty: "Пока нет игроков. Добавьте минимум двух участников.",
        manualCount: "Игроков в списке",
        runDraw: "Провести жеребьёвку",
        drawHelp: "Игроки будут случайно перемешаны и распределены по сетке слева направо. Пустые места станут BYE.",
        errors: {
          title: "Заполните название",
          club: "Выберите бильярдную",
          startsAt: "Выберите дату",
          bracketSize: "Выберите количество участников",
          discipline: "Выберите дисциплину",
          category: "Выберите категорию",
          tournamentType: "Выберите тип турнира",
          format: "Выберите формат",
          bracketType: "Выберите тип сетки",
          prizePool: "Проверьте призовой фонд",
          manualMinimum: "Добавьте минимум двух игроков",
          manualTooMany: "Игроков больше, чем мест в сетке",
          manualDuplicate: "Имена участников должны быть уникальными",
          manualEmptyName: "Введите имя игрока"
        }
      }
    },
    club: {
      eyebrow: "Club dashboard",
      title: "Панель управления клубом",
      subtitle: "Профиль клуба, столы, контакты и бронирования без лишних переходов.",
      profileTitle: "Профиль клуба",
      profileSubtitle: "Эти данные видны игрокам на публичной странице клуба.",
      address: "Адрес",
      contacts: "Контакты",
      tables: "Столы",
      bookings: "Брони клуба",
      bookingSubtitle: "Ближайшие брони и статусы, которыми управляет клуб.",
      tableManagement: "Управление столами",
      tableSubtitle: "Эти столы используются в реальном бронировании на сайте.",
      activeBookings: "Активные брони",
      upcomingBookings: "Ближайшие брони",
      cancelledBookings: "Отмененные брони",
      updateClub: "Обновить клуб",
      addTable: "Добавить стол",
      viewBookings: "Посмотреть брони",
      noClub: "Профиль клуба пока не создан.",
      noTables: "Столы пока не добавлены.",
      noBookings: "Броней пока нет.",
      clubUpdated: "Клуб обновлен.",
      tableAdded: "Стол добавлен.",
      bookingUpdated: "Статус брони обновлен.",
      region: "Регион",
      district: "Район",
      coverUrl: "Ссылка на обложку",
      services: "Услуги через запятую",
      tableName: "Название стола",
      tableKind: "Тип стола",
      minBooking: "Мин. бронь",
      maxBooking: "Макс. бронь",
      defaultTableKind: "Свободная пирамида"
    },
    player: {
      eyebrow: "Player dashboard",
      title: "Личный кабинет игрока",
      subtitle: "Турниры, заявки, брони и результаты игрока в простом виде.",
      profileTitle: "Мой профиль",
      profileSubtitle: "Основная игровая информация и текущий рейтинг.",
      tournaments: "Мои турниры",
      applications: "Мои заявки",
      bookings: "Мои брони",
      results: "Мои результаты",
      activeBookings: "Активные брони",
      elo: "ELO",
      winsLosses: "Победы / поражения",
      findTournament: "Найти турнир",
      findClub: "Забронировать",
      viewBookings: "Мои брони",
      noProfile: "Профиль игрока пока не создан.",
      noActivity: "У вас пока нет турниров и броней. Начните с турнира или бронирования.",
      noBookings: "Броней пока нет.",
      noApplications: "Заявок пока нет.",
      bookingCancelled: "Бронь отменена."
    }
  },
  uz: {
    common: {
      loading: "Kabinet yuklanmoqda",
      noData: "Bu bo'limda hozircha ma'lumot yo'q.",
      open: "Ochish",
      manage: "Boshqarish",
      status: "Holat",
      date: "Sana",
      all: "Jami",
      active: "Faol",
      pending: "Kutilmoqda",
      upcoming: "Yaqin",
      cancelled: "Bekor qilingan",
      completed: "Tugagan",
      bracketReady: "Setka tayyor",
      bracketNeeded: "Setka kerak",
      noBracket: "Setka yo'q",
      profile: "Profil",
      quickActions: "Tezkor amallar",
      latestActivity: "So'nggi faollik",
      emptyActivity: "Hozircha yangi voqealar yo'q.",
      table: "Stol",
      player: "O'yinchi",
      club: "Klub",
      tournament: "Turnir",
      booking: "Bron",
      application: "Ariza"
    },
    admin: {
      eyebrow: "Admin dashboard",
      title: "Platforma boshqaruvi",
      subtitle: "Foydalanuvchilar, bilyard joylari, turnirlar, bronlar va arizalar bo'yicha umumiy holat.",
      users: "Foydalanuvchilar",
      clubs: "Bilyard joylari",
      tournaments: "Turnirlar",
      bookings: "Bronlar",
      pendingApplications: "Moderatsiyadagi arizalar",
      actionsTitle: "Boshqaruvga tez kirish",
      activityTitle: "So'nggi voqealar",
      activitySubtitle: "Haqiqiy foydalanuvchilar, turnirlar, arizalar va bronlardan yig'ildi.",
      actions: {
        tournaments: "Turnirlarni boshqarish",
        clubs: "Bilyard joylarini boshqarish",
        applications: "Arizalarni tekshirish",
        users: "Foydalanuvchilarni boshqarish",
        news: "Yangiliklarni boshqarish"
      },
      actionDescriptions: {
        tournaments: "Yaratish, statuslar, setkalar va public turnir kartasi.",
        clubs: "Joy profillari, manzil, stollar va kontaktlar.",
        applications: "O'yinchi arizalarini tasdiqlash yoki rad etish.",
        users: "Rollar, kirish huquqi va akkaunt tekshiruvi.",
        news: "Platforma yangiliklari."
      },
      emptyBookings: "Hozircha bronlar yo'q.",
      emptyApplications: "Yangi arizalar yo'q."
    },
    organizer: {
      eyebrow: "Organizer dashboard",
      title: "Tashkilotchi kabineti",
      subtitle: "Turnirlar, arizalar, ishtirokchilar puli va setka holati bitta joyda.",
      create: "Turnir yaratish",
      myTournaments: "Mening turnirlarim",
      myTournamentsSubtitle: "Yaqin va faol turnirlar, keyingi amal bo'yicha ko'rsatma bilan.",
      upcoming: "Yaqin turnirlar",
      liveFinished: "Live va tugagan",
      pendingApplications: "Arizalar kutilmoqda",
      participantPool: "Ishtirokchilar puli",
      bracketStatus: "Setka holati",
      needsResult: "Natijalar kerak",
      generateBracket: "Setka yaratish",
      moderate: "Arizalarni moderatsiya qilish",
      openTournament: "Turnirni ochish",
      noTournaments: "Sizda hozircha turnir yo'q. Ro'yxat ochish uchun birinchi turnirni yarating.",
      noAttention: "Hozircha shoshilinch amal yo'q.",
      createTitle: "Yangi turnir",
      createSubtitle: "Minimal forma ishchi turnir yaratadi. Reglament va setka boshqaruv sahifasida sozlanadi.",
      successCreated: "Turnir yaratildi.",
      createClub: "Bron qilishni ochish",
      noClubForTournament: "Mavjud bilyard joyi yo'q. Administratorga murojaat qiling.",
      createFailed: "Turnir yaratilmadi. Maydonlarni tekshirib, qayta urinib ko'ring.",
      drawCompleted: "Qur'a tashlandi. Setka yaratildi, turnir LIVE holatiga o'tkazildi.",
      form: {
        mainBlock: "Asosiy ma'lumotlar",
        mainBlockHelp: "Turnir nomi, o'tkaziladigan joyi va intizomi.",
        paramsBlock: "Turnir parametrlari",
        paramsBlockHelp: "Setka hajmi, mukofot jamg'armasi va turnir holati.",
        publicBlock: "Ommaviy ma'lumot",
        publicBlockHelp: "Bu matnlarni o'yinchilar turnir sahifasida ko'radi.",
        title: "Turnir nomi",
        titlePlaceholder: "Masalan: Tashkent Open 2026",
        startsAt: "Boshlanish sanasi va vaqti",
        startsAtPlaceholder: "Boshlanish sanasi va vaqtini tanlang",
        club: "Bilyard joyi (turnir o'tadigan joy)",
        clubEmptyOption: "Avval administrator orqali bilyard joyini qo'shing",
        discipline: "Intizom",
        category: "Kategoriya",
        tournamentType: "Turnir turi",
        format: "Format",
        bracketType: "Setka turi",
        prizePool: "Mukofot jamg'armasi (so'm)",
        prizePoolPlaceholder: "Masalan: 500000",
        prizePoolHelp: "Turnirning umumiy mukofot jamg'armasi",
        bracketSize: "Ishtirokchilar soni",
        bracketSizeHelp: "Setkada nechta o'yinchi bo'ladi (2, 4, 8, 16, 32, 64)",
        status: "Turnir holati",
        statusHelp: "Ro'yxat ochiq — o'yinchilar ariza yuborishi mumkin",
        registrationLabel: "O'yinchilar ko'radigan status",
        registrationLabelPlaceholder: "Masalan: Ro'yxat 10-maygacha ochiq",
        description: "Turnir tavsifi",
        descriptionPlaceholder: "Qoidalar, qatnashish shartlari va turnir xususiyatlarini yozing",
        participantMode: "Ishtirokchilarni yig'ish turi",
        applicationsMode: "Arizalar orqali",
        manualMode: "Qo'lda qur'a tashlash",
        participantModeHelp: "Arizalar orqali — moderatsiya bilan hozirgi flow. Qo'lda qur'a — ismlarni kiriting va darhol setka yarating.",
        manualListTitle: "Ishtirokchilar ro'yxati",
        manualListHelp: "Haqiqiy o'yinchi ismlarini kiriting. User yaratilmaydi — ishtirokchilar faqat shu setkada ism sifatida saqlanadi.",
        participantNamePlaceholder: "Masalan: Ali",
        addParticipant: "O'yinchi qo'shish",
        removeParticipant: "O'chirish",
        participantNameLabel: "O'yinchi ismi",
        manualEmpty: "Hozircha o'yinchi yo'q. Kamida ikki ishtirokchi qo'shing.",
        manualCount: "Ro'yxatdagi o'yinchilar",
        runDraw: "Qur'a tashlash",
        drawHelp: "O'yinchilar tasodifiy aralashtiriladi va setkaga chapdan o'ngga joylanadi. Bo'sh joylar BYE bo'ladi.",
        errors: {
          title: "Turnir nomini to'ldiring",
          club: "Bilyard joyini tanlang",
          startsAt: "Sanani tanlang",
          bracketSize: "Ishtirokchilar sonini tanlang",
          discipline: "Intizomni tanlang",
          category: "Kategoriyani tanlang",
          tournamentType: "Turnir turini tanlang",
          format: "Formatni tanlang",
          bracketType: "Setka turini tanlang",
          prizePool: "Mukofot jamg'armasini tekshiring",
          manualMinimum: "Kamida ikki o'yinchi qo'shing",
          manualTooMany: "O'yinchilar soni setkadagi joylardan ko'p",
          manualDuplicate: "Ishtirokchi ismlari takrorlanmasligi kerak",
          manualEmptyName: "O'yinchi ismini kiriting"
        }
      }
    },
    club: {
      eyebrow: "Club dashboard",
      title: "Klub boshqaruvi",
      subtitle: "Klub profili, stollar, kontaktlar va bronlar bitta kabinetda.",
      profileTitle: "Klub profili",
      profileSubtitle: "Bu ma'lumotlar klubning public sahifasida ko'rinadi.",
      address: "Manzil",
      contacts: "Kontaktlar",
      tables: "Stollar",
      bookings: "Klub bronlari",
      bookingSubtitle: "Klub boshqaradigan yaqin bronlar va statuslar.",
      tableManagement: "Stollarni boshqarish",
      tableSubtitle: "Bu stollar saytdagi real bron qilishda ishlatiladi.",
      activeBookings: "Faol bronlar",
      upcomingBookings: "Yaqin bronlar",
      cancelledBookings: "Bekor qilingan bronlar",
      updateClub: "Klubni yangilash",
      addTable: "Stol qo'shish",
      viewBookings: "Bronlarni ko'rish",
      noClub: "Klub profili hali yaratilmagan.",
      noTables: "Hozircha stollar yo'q.",
      noBookings: "Hozircha bronlar yo'q.",
      clubUpdated: "Klub yangilandi.",
      tableAdded: "Stol qo'shildi.",
      bookingUpdated: "Bron holati yangilandi.",
      region: "Hudud",
      district: "Tuman",
      coverUrl: "Muqova havolasi",
      services: "Xizmatlar, vergul bilan",
      tableName: "Stol nomi",
      tableKind: "Stol turi",
      minBooking: "Min. bron",
      maxBooking: "Maks. bron",
      defaultTableKind: "Erkin piramida"
    },
    player: {
      eyebrow: "Player dashboard",
      title: "O'yinchi kabineti",
      subtitle: "Turnirlar, arizalar, bronlar va natijalar sodda ko'rinishda.",
      profileTitle: "Mening profilim",
      profileSubtitle: "Asosiy o'yin ma'lumotlari va joriy reyting.",
      tournaments: "Mening turnirlarim",
      applications: "Mening arizalarim",
      bookings: "Mening bronlarim",
      results: "Mening natijalarim",
      activeBookings: "Faol bronlar",
      elo: "ELO",
      winsLosses: "G'alaba / mag'lubiyat",
      findTournament: "Turnir topish",
      findClub: "Bron qilish",
      viewBookings: "Mening bronlarim",
      noProfile: "O'yinchi profili hali yaratilmagan.",
      noActivity: "Sizda hozircha turnir yoki bron yo'q. Turnir yoki bron qilishdan boshlang.",
      noBookings: "Hozircha bronlar yo'q.",
      noApplications: "Hozircha arizalar yo'q.",
      bookingCancelled: "Bron bekor qilindi."
    }
  },
  en: {
    common: {
      loading: "Loading dashboard",
      noData: "No data for this section yet.",
      open: "Open",
      manage: "Manage",
      status: "Status",
      date: "Date",
      all: "Total",
      active: "Active",
      pending: "Pending",
      upcoming: "Upcoming",
      cancelled: "Cancelled",
      completed: "Completed",
      bracketReady: "Bracket ready",
      bracketNeeded: "Generate bracket",
      noBracket: "No bracket",
      profile: "Profile",
      quickActions: "Quick actions",
      latestActivity: "Latest activity",
      emptyActivity: "No recent activity yet.",
      table: "Table",
      player: "Player",
      club: "Club",
      tournament: "Tournament",
      booking: "Booking",
      application: "Application"
    },
    admin: {
      eyebrow: "Admin dashboard",
      title: "Platform control center",
      subtitle: "Users, billiard places, tournaments, bookings, and applications on one operational page.",
      users: "Users",
      clubs: "Billiard places",
      tournaments: "Tournaments",
      bookings: "Bookings",
      pendingApplications: "Pending applications",
      actionsTitle: "Quick management access",
      activityTitle: "Latest activity summary",
      activitySubtitle: "Built from real users, tournaments, applications, and bookings.",
      actions: {
        tournaments: "Open tournament management",
        clubs: "Open place management",
        applications: "Review applications",
        users: "Manage users",
        news: "Manage news"
      },
      actionDescriptions: {
        tournaments: "Creation, statuses, brackets, and public tournament cards.",
        clubs: "Place profiles, addresses, tables, and contact details.",
        applications: "Approve and reject player applications.",
        users: "Roles, access, and account verification.",
        news: "Platform posts and updates."
      },
      emptyBookings: "No bookings yet.",
      emptyApplications: "No new applications."
    },
    organizer: {
      eyebrow: "Organizer dashboard",
      title: "Organizer workspace",
      subtitle: "Tournaments, applications, participant pools, and bracket state in one workspace.",
      create: "Create tournament",
      myTournaments: "My tournaments",
      myTournamentsSubtitle: "Upcoming and active tournaments with the next action made clear.",
      upcoming: "Upcoming tournaments",
      liveFinished: "Live and finalized",
      pendingApplications: "Applications waiting",
      participantPool: "Participant pool",
      bracketStatus: "Bracket state",
      needsResult: "Results needed",
      generateBracket: "Generate bracket",
      moderate: "Moderate applications",
      openTournament: "Open tournament",
      noTournaments: "You do not have tournaments yet. Create the first one to open registration and collect participants.",
      noAttention: "No urgent actions right now.",
      createTitle: "New tournament",
      createSubtitle: "The minimal form creates a working tournament. Details, regulation, and bracket are managed inside the tournament.",
      successCreated: "Tournament created.",
      createClub: "Open booking",
      noClubForTournament: "No billiard places are available. Contact an administrator.",
      createFailed: "Could not create the tournament. Check the fields and try again.",
      drawCompleted: "Draw completed. The bracket was created and the tournament is now LIVE.",
      form: {
        mainBlock: "Main details",
        mainBlockHelp: "Tournament name, venue, and discipline.",
        paramsBlock: "Tournament settings",
        paramsBlockHelp: "Bracket size, prize fund, and tournament status.",
        publicBlock: "Public information",
        publicBlockHelp: "Players will see these texts on the tournament page.",
        title: "Tournament title",
        titlePlaceholder: "For example: Tashkent Open 2026",
        startsAt: "Start date and time",
        startsAtPlaceholder: "Choose start date and time",
        club: "Billiard place (where the tournament takes place)",
        clubEmptyOption: "Add a billiard place through an administrator first",
        discipline: "Discipline",
        category: "Category",
        tournamentType: "Tournament type",
        format: "Format",
        bracketType: "Bracket type",
        prizePool: "Prize fund (UZS)",
        prizePoolPlaceholder: "For example: 500000",
        prizePoolHelp: "Total tournament prize fund",
        bracketSize: "Number of participants",
        bracketSizeHelp: "How many players will be in the bracket (2, 4, 8, 16, 32, 64)",
        status: "Tournament status",
        statusHelp: "Registration means players can submit applications",
        registrationLabel: "Status for players (what they see)",
        registrationLabelPlaceholder: "For example: Registration is open until May 10",
        description: "Tournament description",
        descriptionPlaceholder: "Describe rules, participation terms, and tournament details",
        participantMode: "Participant intake type",
        applicationsMode: "Through applications",
        manualMode: "Manual draw",
        participantModeHelp: "Applications keeps the current moderation flow. Manual draw lets you enter names and create the bracket immediately.",
        manualListTitle: "Participant list",
        manualListHelp: "Enter real player names. No users are created; participants are stored as names for this bracket only.",
        participantNamePlaceholder: "For example: Ali",
        addParticipant: "Add player",
        removeParticipant: "Remove",
        participantNameLabel: "Player name",
        manualEmpty: "No players yet. Add at least two participants.",
        manualCount: "Players in list",
        runDraw: "Run draw",
        drawHelp: "Players will be shuffled randomly and placed into the bracket from left to right. Empty slots become BYE.",
        errors: {
          title: "Enter tournament title",
          club: "Choose a billiard place",
          startsAt: "Choose a date",
          bracketSize: "Choose number of participants",
          discipline: "Choose a discipline",
          category: "Choose a category",
          tournamentType: "Choose a tournament type",
          format: "Choose a format",
          bracketType: "Choose a bracket type",
          prizePool: "Check the prize fund",
          manualMinimum: "Add at least two players",
          manualTooMany: "There are more players than bracket slots",
          manualDuplicate: "Participant names must be unique",
          manualEmptyName: "Enter player name"
        }
      }
    },
    club: {
      eyebrow: "Club dashboard",
      title: "Club operations panel",
      subtitle: "Club profile, tables, contacts, and bookings without extra navigation.",
      profileTitle: "Club profile",
      profileSubtitle: "These details are visible to players on the public club page.",
      address: "Address",
      contacts: "Contacts",
      tables: "Tables",
      bookings: "Club bookings",
      bookingSubtitle: "Upcoming bookings and statuses managed by the club.",
      tableManagement: "Table management",
      tableSubtitle: "These tables power real booking on the website.",
      activeBookings: "Active bookings",
      upcomingBookings: "Upcoming bookings",
      cancelledBookings: "Cancelled bookings",
      updateClub: "Update club",
      addTable: "Add table",
      viewBookings: "View bookings",
      noClub: "Club profile is not created yet.",
      noTables: "No tables yet.",
      noBookings: "No bookings yet.",
      clubUpdated: "Club updated.",
      tableAdded: "Table added.",
      bookingUpdated: "Booking status updated.",
      region: "Region",
      district: "District",
      coverUrl: "Cover URL",
      services: "Services, comma-separated",
      tableName: "Table name",
      tableKind: "Table type",
      minBooking: "Min booking",
      maxBooking: "Max booking",
      defaultTableKind: "Free pyramid"
    },
    player: {
      eyebrow: "Player dashboard",
      title: "Player dashboard",
      subtitle: "Tournaments, applications, bookings, and results in a simple personal view.",
      profileTitle: "My profile",
      profileSubtitle: "Core playing data and current rating.",
      tournaments: "My tournaments",
      applications: "My applications",
      bookings: "My bookings",
      results: "My results",
      activeBookings: "Active bookings",
      elo: "ELO",
      winsLosses: "Wins / losses",
      findTournament: "Find tournament",
      findClub: "Book",
      viewBookings: "My bookings",
      noProfile: "Player profile is not created yet.",
      noActivity: "You do not have tournaments or bookings yet. Start with a tournament or booking.",
      noBookings: "No bookings yet.",
      noApplications: "No applications yet.",
      bookingCancelled: "Booking cancelled."
    }
  }
} as const;

export function dashboardCopy(locale: Locale) {
  return copy[locale];
}
