CREATE TYPE "BilliardKind" AS ENUM ('PYRAMID', 'POOL', 'SNOOKER');
CREATE TYPE "TournamentCategory" AS ENUM ('MEN', 'WOMEN', 'JUNIORS', 'GIRLS', 'AMATEURS', 'PROFESSIONALS', 'OPEN', 'TEAM', 'PERSONAL');
CREATE TYPE "TournamentLevel" AS ENUM ('OPEN_TOURNAMENT', 'CHAMPIONSHIP', 'CUP', 'LEAGUE', 'RATED_TOURNAMENT', 'FRIENDLY_TOURNAMENT', 'CLUB_TOURNAMENT');
CREATE TYPE "TournamentFormat" AS ENUM ('INDIVIDUAL', 'TEAM', 'TEAM_2X2', 'TEAM_3X3');
CREATE TYPE "TournamentBracketSystem" AS ENUM ('SINGLE_ELIMINATION', 'DOUBLE_ELIMINATION', 'ROUND_ROBIN', 'SWISS', 'GROUP_PLAYOFF');
CREATE TYPE "ParticipantSelectionMode" AS ENUM ('APPLICATIONS', 'MANUAL_DRAW');

ALTER TABLE "Tournament"
  ADD COLUMN "billiardKind" "BilliardKind" NOT NULL DEFAULT 'PYRAMID',
  ADD COLUMN "category" "TournamentCategory" NOT NULL DEFAULT 'OPEN',
  ADD COLUMN "tournamentLevel" "TournamentLevel" NOT NULL DEFAULT 'OPEN_TOURNAMENT',
  ADD COLUMN "eventFormat" "TournamentFormat" NOT NULL DEFAULT 'INDIVIDUAL',
  ADD COLUMN "bracketSystem" "TournamentBracketSystem" NOT NULL DEFAULT 'SINGLE_ELIMINATION',
  ADD COLUMN "participantSelectionMode" "ParticipantSelectionMode" NOT NULL DEFAULT 'APPLICATIONS';
